name: Solinia3Chat
main: com.solinia.solinia.chat.Solinia3ChatPlugin
version: 1.0
commands:
  trance:
    description: Displays additional information about Solinia3Chat
    usage: /soliniachat
    alias: []
depend:
- Solinai3Chat
softdepend:
