name: Solinia3Core
main: com.solinia.solinia.Solinia3CorePlugin
version: 1.0
commands:
  solinia:
    description: Displays additional information about Solinia3Core
    usage: /solinia
    aliases: []
  commit:
    description: Commits Solinia3Core State Data
    usage: /commit
    aliases: []
  forename:
    description: Sets player forename
    usage: /forename <forename>
    aliases:
    - name
    - nick
  lastname:
    description: Sets player lastname
    usage: /lastname <lastname>
    aliases: 
    - surname
  mana:
    description: Gets player mana
    usage: /mana
    aliases: []
  addrace:
    description: Creates a new race
    usage: /addrace racename strength stamina agility dexterity wisdom intelligence charisma adminonly
    aliases:
    - createrace
  setrace:
    description: Sets a players race
    usage: /setrace racename
    aliases:
    - race
  addclass:
    description: Creates a new class
    usage: /addclass classname adminonly
    aliases:
    - createclass
  setclass:
    description: Sets a players class
    usage: /setclass classname
    aliases:
    - class
  addraceclass:
    description: Adds a class to a race
    usage: /addraceclass racename classname
    aliases: []
  stats:
    description: Gets player core stats
    usage: /stats
    aliases: []
  who:
    description: Lists online player details
    usage: /who
    aliases: []
  resetplayer:
    description: Resets players to a default state
    usage: /resetplayer <mcaccountname>
    aliases: []
  setgender:
    description: Sets players gender
    usage: /setgender male/female
    aliases: []
  emote:
    description: Emotes a message
    usage: /emote action
    aliases:
    - me
  roll:
    description: Rolls a dice
    usage: /roll sides
    aliases:
    - random
    - dice
  setlanguage:
    description: Sets players language
    usage: /setlanguage language
    aliases:
    - language
  tarot:
    description: Deals a tarot card
    usage: /tarot
    aliases: []
  skills:
    description: Lists player skills
    usage: /skills
    aliases: []
  createitem:
    description: Creates item from the item you are holding
    usage: /createitem
    aliases: []
  listitems:
    description: Lists items
    usage: /listitems searchstring
    aliases: []
  spawnitem:
    description: Spawns an item
    usage: /spawnitem itemid
    aliases: []
  spawnrandomitem:
    description: Spawns a random item
    usage: /spawnrandomitem
    aliases: []
  raceinfo:
    description: Lists race info
    usage: /raceinfo
    aliases: []
  rebuildspellitems:
    description: Rebuilds spell items
    usage: /rebuildspellitems
    aliases: []
  createnpc:
    description: Creates a new npc
    usage: /createnpc factionid level npcname
    aliases:
    - addnpc
  createnpccopy:
    description: Creates a new npc from an existing npc
    usage: /createnpc ncpid npcname
    aliases:
    - addnpccopy
  createfaction:
    description: Creates a new faction
    usage: /createfaction basestandingvalue name
    aliases:
    - addfaction
  listfactions:
    description: Lists factions
    usage: /listfactions filter
    aliases: []
  listnpcs:
    description: Lists npcs
    usage: /listnpcs filter
    aliases: []
  editnpc:
    description: Edits an npc
    usage: /editnpc npcid setting value
    aliases: []
  createloottable:
    description: Creates a new loot table
    usage: /createloottable name
    aliases: []
  createlootdrop:
    description: Creates a new loot drop table
    usage: /createlootdrop name
    aliases: []
  addlootdropitem:
    description: Adds an item to a loot drop
    usage: /addlootdropitem lootdropid itemid count always chance
    aliases: []
  addloottablelootdrop:
    description: Adds a loot drop table to a loot table
    usage: /addloottablelootdrop loottableid lootdropid
    aliases: []
  editspell:
    description: Edits a spell
    usage: /editspell spellid setting value
    aliases: []
  listloottables:
    description: Lists loottables
    usage: /listloottables filter
    aliases: []
  listlootdrops:
    description: Lists lootdrops
    usage: /listlootdrops filter
    aliases: []
  local:
    description: Speaks in local chat
    usage: /local message
    aliases:
    - say
    - l
  forcelevel:
    description: Forces a players level
    usage: /forcelevel mcplayer level
    aliases: []
  createmerchantlist:
    description: Creates a merchant list
    usage: /createmerchantlist name
    aliases: []
  addmerchantitem:
    description: adds an item to a merchant list
    usage: /addmerchantitem merchantid itemid
    aliases: []
  npcbuy:
    description: buys an item from an npc merchant
    usage: /npcbuy itemid count
    aliases: []
  npcsell:
    description: sells an item to an npc merchant
    usage: /npcsell itemid count
    aliases: []
  listmerchantlists:
    description: Lists all merchant lists
    usage: /listmerchantlists
    aliases:
    - listmerchants
  edititem:
    description: Edits an item
    usage: /edititem itemid setting value
    aliases: []
  editclass:
    description: Edits a class
    usage: /edititem classid setting value
    aliases: []
  createspawngroup:
    description: Creates a new spawngroup
    usage: /createspawngroup npcid spawngroupname
    aliases: []
  listspawngroups:
    description: Lists spawngroups
    usage: /listspawngroups filter
    aliases: []
  updatespawngrouploc:
    description: Updates a spawngroups location
    usage: /updatespawngrouploc spawngroupid
    aliases: []
  setchannel:
    description: Sets current channel
    usage: /setchannel channelname
    aliases:
    - ch
  ooc:
    description: Sends a message to the ooc channel
    usage: /ooc message
    aliases: []
  group:
    description: Group control commands
    usage: /group cmd
    aliases:
    - grp
    - grou
  groupchat:
    description: Sends a message to the group channel
    usage: /groupchat message
    aliases:
    - g
    - gc
  convertmerchanttolootdrop:
    description: Sends a message to the ooc channel
    usage: /convertmerchanttolootdrop merchantid
    aliases:
    - convertmerchant
  perks:
    description: Perk help
    usage: /perks
    aliases: []
  effects:
    description: Lists details regarding effects related to your character
    usage: /effects
    aliases: []
  createarmorset:
    description: Creates a new set of armour for a class
    usage: /createarmorset classid tier suffixname
    aliases: 
    - createarmourset
  listspells:
    description: Lists spells
    usage: /listspells searchstring
    aliases: []
  viewlootdrop:
    description: Views a loot drop
    usage: /viewlootdrop lootdropid
    aliases: []
  viewloottable:
    description: Views a loottable
    usage: /viewloottable loottableid
    aliases: []
depend:
softdepend:
- Vault
- Essentials
- MythicMobs
