name: Solinia3Core
main: com.solinia.solinia.Solinia3CorePlugin
version: 1.0
commands:
  solinia:
    description: Displays additional information about Solinia3Core
    usage: /solinia
    alias: []
  commit:
    description: Commits Solinia3Core State Data
    usage: /commit
    alias: []
  forename:
    description: Sets player forename
    usage: /forename <forename>
    alias:
    - name
    - nick
  lastname:
    description: Sets player lastname
    usage: /lastname <lastname>
    alias: 
    - surname
  mana:
    description: Gets player mana
    usage: /mana
    alias: []
  addrace:
    description: Creates a new race
    usage: /setrace racename strength stamina agility dexterity wisdom intelligence charisma adminonly
    alias:
    - createrace
  setrace:
    description: Sets a players race
    usage: /setrace racename
    alias:
    - race
  addclass:
    description: Creates a new class
    usage: /addclass classname adminonly
    alias:
    - createclass
  setclass:
    description: Sets a players class
    usage: /setclass classname
    alias:
    - class
  addraceclass:
    description: Adds a class to a race
    usage: /addraceclass racename classname
    alias: []
depend:
softdepend:
- Vault
- Essentials
