name: Solinia3Core
main: com.solinia.solinia.Solinia3CorePlugin
version: 1.0
commands:
  solinia:
    description: Displays additional information about Solinia3Core
    usage: /solinia
    aliases: []
  commit:
    description: Commits Solinia3Core State Data
    usage: /commit
    aliases: []
  forename:
    description: Sets player forename
    usage: /forename <forename>
    aliases:
    - name
    - nick
  lastname:
    description: Sets player lastname
    usage: /lastname <lastname>
    aliases: 
    - surname
  mana:
    description: Gets player mana
    usage: /mana
    aliases: []
  addrace:
    description: Creates a new race
    usage: /addrace racename strength stamina agility dexterity wisdom intelligence charisma adminonly
    aliases:
    - createrace
  setrace:
    description: Sets a players race
    usage: /setrace racename
    aliases:
    - race
  addclass:
    description: Creates a new class
    usage: /addclass classname adminonly
    aliases:
    - createclass
  setclass:
    description: Sets a players class
    usage: /setclass classname
    aliases:
    - class
  addraceclass:
    description: Adds a class to a race
    usage: /addraceclass racename classname
    aliases: []
  stats:
    description: Gets player core stats
    usage: /stats
    aliases: []
  who:
    description: Lists online player details
    usage: /who
    aliases: []
  resetplayer:
    description: Resets players to a default state
    usage: /resetplayer <mcaccountname>
    aliases: []
  setgender:
    description: Sets players gender
    usage: /setgender male/female
    aliases: []
  emote:
    description: Emotes a message
    usage: /emote action
    aliases:
    - me
  roll:
    description: Rolls a dice
    usage: /roll sides
    aliases:
    - random
    - dice
  setlanguage:
    description: Sets players language
    usage: /setgender language
    aliases: []
  tarot:
    description: Deals a tarot card
    usage: /tarot
    aliases: []
  skills:
    description: Lists player skills
    usage: /skills
    aliases: []
depend:
softdepend:
- Vault
- Essentials
