name: Solinia3Core
main: com.solinia.solinia.Solinia3CorePlugin
version: 1.0
commands:
  solinia:
    description: Displays additional information about Solinia3Core
    usage: /solinia
    alias: []
  commit:
    description: Commits Solinia3Core State Data
    usage: /commit
    alias: []
depend:
softdepend:
- Vault
- Essentials
